{"name": "test_divide", "status": "skipped", "statusDetails": {"message": "AssertionError: assert 2.9999999999999996 == 3.0\n +  where 2.9999999999999996 = <function Calculator.divide at 0x00000137B13273A8>(0.3, 0.1)\n +    where <function Calculator.divide at 0x00000137B13273A8> = Calculator.divide", "trace": "self = <test.test_calculator.TestCalculator object at 0x00000137B132F948>, setup_calculator = <src.Calculator.Calculator object at 0x00000137B1339CC8>\n\n    @pytest.mark.xfail(condition=lambda: True, reason='this test is expecting failure')\n    def test_divide(self, setup_calculator):\n>       assert Calculator.divide(0.3, 0.1) == 3.0\nE       assert 2.9999999999999996 == 3.0\nE        +  where 2.9999999999999996 = <function Calculator.divide at 0x00000137B13273A8>(0.3, 0.1)\nE        +    where <function Calculator.divide at 0x00000137B13273A8> = Calculator.divide\n\ntest\\test_calculator.py:25: AssertionError"}, "start": 1604533721028, "stop": 1604533721028, "uuid": "49fac99e-c000-4c10-b7df-0f26e7a1cd98", "historyId": "72585ac4fb3239621774b08068d57f0f", "testCaseId": "57a825a7c480b32271483d1fd0c27224", "fullName": "test.test_calculator.TestCalculator#test_divide", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(condition=<function TestCalculator.<lambda> at 0x00000137B13275E8>, reason='this test is expecting failure')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_calculator"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "DESKTOP-9B9M95V"}, {"name": "thread", "value": "29472-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_calculator"}]}